### ISSUE TITLE
ldp4j-build parent not present in central repository

### ISSUE THREAD

**Issue by rnavarropiris** [ldp4j/ldp4j#12]
# Problem description

When importing in the following Eclipse IDE
```
Spring Tool Suite 

Version: 3.6.3.RELEASE
Build Id: 201411281415
Platform: Eclipse Luna SR1 (4.4.1)
```
I get the following error:

```
Project build error: Non-resolvable parent POM: Could not find artifact org.ldp4j:ldp4j-build:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong 
 local POM
```

I think it is because it is not present in the [central repository](https://search.maven.org/#search|ga|1|ldp4j-build).

# Proposed solution
 Either
* add the library to the central repository, or
* add a public repository containing the dependencies (if existing)

**Comment by mestebangutierrez** [comment]
We have everything arranged for publishing in Maven Central. However, we don't have a final release, and therefore we cannot deploy to Maven Central yet (see why [here](http://central.sonatype.org/pages/ossrh-guide.html)). 

Nevertheless, the snapshots are made available in [Sonatype's OSS Snapshot Repository](https://oss.sonatype.org/content/groups/public/), that you can configure in your Maven settings as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings 
  xmlns="http://maven.apache.org/SETTINGS/1.0.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation=
    "http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <!-- Other configuration here -->
  <profiles>
    <profile>
      <id>ldp4j</id>
      <activation><!-- Activation configuration here --></activation>
      <repositories>
        <repository>
          <id>sonatype-oss-public-snapshots</id>
          <url>https://oss.sonatype.org/content/groups/public/</url>
          <snapshots><enabled>true</enabled></snapshots>
          <releases><enabled>false</enabled></releases>
        </repository>
      </repositories>
    </profile>
  </profiles>
</settings>
```
