### ISSUE TITLE
How to define and use REST API of a ldp4j backend app?

### ISSUE THREAD

**Issue by nam-vuhoang** [ldp4j/ldp4j#18]
Let's say if I want to define an REST API as specified in the LDP4J example:

• Manage persons:
• POST {base}/persons/
• GET {base}/persons/{pid}/
• PUT {base}/persons/{pid}/
• DELETE {base}/persons/{pid}/

then which methods I have to use?

I've found this gragment in the MyApplication.setup() from https://github.com/ldp4j/ldp4j/blob/master/framework/application/examples/src/main/java/org/ldp4j/example/MyApplication.java: 

environment.publishResource(
    NamingScheme.getDefault().name("PersonResource"),
    PersonHandler.class,
    "rootPersonResource/");
environment.publishResource(
   NamingScheme.getDefault().name("PersonContainer"),
   PersonContainerHandler.class,
  "rootPersonContainer/");

Note that there is no string equal to "persons" used. 

Here are the results I get when I try to connect from Google Chrome ({base}=http://localhost:port/webapp-name):

{base}/persons/ --> "No service was found"
{base}/rootPersonResource/ --> "No service was found"
{base}/rootPersonContainer/ --> "No service was found"
{base}/any-other-name-except-ldp4j/ --> "No service was found"
{base}/ldp4j/ --> ""
{base}/ldp4j/api/ --> "No endpoint found".

**Comment by mestebangutierrez** [comment]
Have you had a look at the LDP4j tutorial we held @ ESWC-2015? I suggest you to go over it, as the examples in the LDP4j repository are more geared towards the tests executed during the build process. 

You can find the tutorial materials in http://www.ldp4j.org/tutorials/eswc2015/. Part of the materials is a hands-on example application. Have a look at the slides and the source code. I hope those materials are clear enough.

**Comment by nam-vuhoang** [comment]
Yes. Of course.

This is what I could find from the tutorial:

public class MyApplication extends Application<Configuration> {
 @Override
 public void setup(Environment environment, Bootstrap<Configuration> bootstrap) throws ApplicationSetupException {
 MyModifiableContainerHandler containerHandler=new MyModifiableContainerHandler();
 MyDeletableResourceHandler resourceHandler=new MyDeletableResourceHandler();
 // TODO Your handler configuration logic here
 bootstrap.addHandler(resourceHandler);
 bootstrap.addHandler(containerHandler);
 Name<?> rootContainerName=NamingScheme.getDefault().name("containerName") ;

 environment.publishResource(rootContainerName, MyModifiableContainerHandler.class, "containerRootPath");
 }
 @Override
 public void initialize(WriteSession session) throws ApplicationInitializationException {
 // TODO Your handler initialization logic here
 // Remember, the session has to be updated to reflect the state of the data managed by the handlers
 }
 @Override
 public void shutdown() throws ApplicationShutdownException {
 // TODO Your shutdown logic here
 }
}

===============================================

Frontend component design
Exposed API
17
• Manage persons:
• POST {base}/persons/
• GET {base}/persons/{pid}/
• PUT {base}/persons/{pid}/
• DELETE {base}/persons/{pid}/

===============================================

contacts> retrieve-resource http://localhost/contacts/ldp4j/api/persons/

===============================================

Stupid me. I don't understand how they are related to each other.

**Comment by mestebangutierrez** [comment]
Ok. In the hands-on slides are divided into 4 blocks: 1) the recipe for using LDP4j, which provides some examples for creating a *simple* application (just a basic container and a simple resource); 2) the design and architecture of an example Contacts application; 3) some directions on how to develop the described application with LDP4j (or if you prefer, a description of the implementation you may find in the tutorial GitHub repo); and 4) examples on how to use the application using the client component.

Appart from going over the design and architecture of the application, it is a good idea to have a look at the implementation together with the directions (description) provided in the slides, but it is a better to read first the [__LDP4j 101 slides__](http://www.ldp4j.org/tutorials/eswc2015/pdfs/eswc-2015-tutorial-3-LDP4j%20101.pdf). 

There, in slide 8, we introduce the notion of __Template__: the way an application specifies the types of resources managed and how they are (hierarchichally) organized (i.e., membership and attachment) and published (i.e., via relative paths). With this in mind, if you go back to the sourcecode you will see how the API defined in the slides is defined via templates.

**Comment by nam-vuhoang** [comment]
Dear Miguel,

Thank you for your reply and detailed explanations!


Unfortunately, I still cannot access to address {baseuri}/persons (on my
Tomcat it is: http://localhost:8080/drumbeat-test-ldp4j/persons).

I could find no place in the example that mentions about term "persons"
(while there are some places for setting path="address" or path="books",
but no class specifies path="persons" or something like that).

Could you please have a look to the attached project and help to find what
I am doing wrong? The code was copied from the ESWC 2015 tutorial code.

Thank you very much!

Best regards,
Nam

**Comment by mestebangutierrez** [comment]
The point is that you're mixing the examples of the recipe for implementing an LDP4j application shown in the first part of the hands-on slides, with the slides about the description of the API for the hands-on application itself. 

If you have a look at the `ContactsApplication` of the [hands-on](https://github.com/ldp4j/eswc2015-tutorial/blob/master/frontend/core/src/main/java/org/ldp4j/tutorial/frontend/ContactsApplication.java), you'll see the following code within the `setup` method:

    environment.
    		publishResource(
    			this.personContainerName,
    			PersonContainerHandler.class,
    			ROOT_PERSON_CONTAINER_PATH);

This excerpt publishes a resource managed by the `PersonContainerHandler` class, named as defined by `this.personContainerName`, at path `ROOT_PERSON_CONTAINER_PATH` (`persons/`). Thus, requests to `http://localhost:8080/{app-context}/ldp4j/api/persons/`, will be handled to the `PersonContainerHandler`.

Now, according to the organization of the Contacts Application described in the slide #15 of the hands-on slides, you can see that Person resources have an attached Contact container available at `contacts/`.

As a result the available endpoints are:

 - `{base}/persons/`, used for dealing with the collection of persons
   that own a contact list. 
 - `{base}/persons/{pid}/`, used for dealing
   with a particular owner of a contact list.
 -  `{base}/persons/{pid}/contacts/`, used for dealing with the contact list of a particular user.
 - `{base}/persons/{pid}/contacts/{cid}`,
   used for dealing wiht a contact in the contact list of a particular
   user.

Then, by having a look at the interfaces implemented by the resource handlers, we get the operations supported by each endpoint, which match those specified in slide #17 of the hands-on presentation.

Now, going to your application what I see is that you publish a root resource for a Person resource (`rootPersonResource/`) and a Person container (`rootPersonContainer/`) in the setup and later, in the initialization, you attach the a contacts container to the root person resource. 

As persons are ephemeral (can come and go), it does not make sense to have a root person resource. Creating persons and their associated contact containers should be one of the duties of your `PersonContainerHandler`.

I hope this helps clarifying how the REST API is defined for a given LDP4j application, and allows you completing your test application.
